kind: pipeline
name: python-3-7

steps:
- name: test
  image: python:3.7
  commands:
  - pip install -r requirements.txt
  - pwd
  - ls
  - python main.py

- name: deploy
  image: python:3.7
  commands:
  - chmod +x deploy-script.sh
  - ls -l
  - ./deploy-script.sh