kind: pipeline
name: python-3-7

steps:
- name: test
  image: python:3.7
  commands:
  - pip install -r requirements.txt
  - python main.py

- name: deploy
  image: python:3.7
  commands:
  - deploy-script.sh